# Generated by Django 5.0.6 on 2024-10-05 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0004_cec'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CEC',
        ),
    ]
